### ISSUE TITLE
The return value of "from_path" doesn't match the comments in the function

### ISSUE THREAD

**Issue by rfrenchseti** [SETI/rms-pdsfile#5]
From rms-webtools created by [juzen2003](https://github.com/juzen2003): SETI/rms-webtools#24  

- Current from_path expected results based on comments:
  - 'COISS_2001.targz' --> 'archives-volumes/COISS_2xxx/COISS_2001.tar.gz'
  - 'COISS_2001_previews.targz' --> 'archives-previews/COISS_2xxx/COISS_2001_previews.tar.gz'
  - 'COISS_0xxx_tar.gz' -->  'archives-volumes/COISS_2xxx'

- Actual return results from function:
  - 'COISS_2001.targz' --> previews/COISS_2xxx/COISS_2001
  - 'COISS_2001_previews.targz' --> volumes/COISS_2xxx/COISS_2001
  - 'COISS_0xxx_tar.gz' --> 'volumes/COISS_0xxx'

**Comment by rfrenchseti** [comment]
Is this still a problem? All the tests are passing.

**Comment by rfrenchseti** [comment]
Currently the comment says:

```
          diagrams/checksums/whatever -> checksums-diagrams/whatever
          checksums/archives/whatever -> checksums-archives-volumes/whatever
          COISS_2001.targz -> archives-volumes/COISS_2xxx/COISS_2001.tar.gz
          COISS_2001_previews.targz ->
                    archives-previews/COISS_2xxx/COISS_2001_previews.tar.gz
          COISS_0xxx/v1 -> COISS_0xxx_v1
```

but running the code gives:

```
>>> p=pdsfile.Pds3File.from_path('COISS_2001.targz')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/seti/opus/rms-pdsfile/pdsfile/pdsfile.py", line 4218, in from_path
    this = this.child(part, fix_case=True, must_exist=must_exist,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/seti/opus/rms-pdsfile/pdsfile/pdsfile.py", line 3515, in child
    raise ValueError('Illegal bundle set directory "%s": %s' %
ValueError: Illegal bundle set directory "COISS_2001.targz": volumes
```
